# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'EditWindow.ui'
#
# Created by: PyQt5 UI code generator 5.13.2
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(1200, 800)
        self.gridLayout_2 = QtWidgets.QGridLayout(Dialog)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.frame = QtWidgets.QFrame(Dialog)
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.gridLayout = QtWidgets.QGridLayout(self.frame)
        self.gridLayout.setObjectName("gridLayout")
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem, 0, 0, 1, 1)
        self.buttonBox = QtWidgets.QDialogButtonBox(self.frame)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.buttonBox.setFont(font)
        self.buttonBox.setOrientation(QtCore.Qt.Horizontal)
        self.buttonBox.setStandardButtons(QtWidgets.QDialogButtonBox.Cancel|QtWidgets.QDialogButtonBox.Ok)
        self.buttonBox.setCenterButtons(False)
        self.buttonBox.setObjectName("buttonBox")
        self.gridLayout.addWidget(self.buttonBox, 0, 1, 1, 1)
        self.gridLayout_2.addWidget(self.frame, 5, 1, 1, 1)
        self.SongText = QtWidgets.QPlainTextEdit(Dialog)
        font = QtGui.QFont()
        font.setFamily("Courier New")
        font.setPointSize(10)
        self.SongText.setFont(font)
        self.SongText.setObjectName("SongText")
        self.gridLayout_2.addWidget(self.SongText, 4, 0, 1, 2)
        self.frame_2 = QtWidgets.QFrame(Dialog)
        self.frame_2.setMinimumSize(QtCore.QSize(0, 22))
        self.frame_2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_2.setObjectName("frame_2")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.frame_2)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label = QtWidgets.QLabel(self.frame_2)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.horizontalLayout.addWidget(self.label)
        self.FName = QtWidgets.QLineEdit(self.frame_2)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.FName.setFont(font)
        self.FName.setObjectName("FName")
        self.horizontalLayout.addWidget(self.FName)
        self.SongKey = QtWidgets.QComboBox(self.frame_2)
        self.SongKey.setMinimumSize(QtCore.QSize(90, 0))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.SongKey.setFont(font)
        self.SongKey.setObjectName("SongKey")
        self.SongKey.addItem("")
        self.SongKey.addItem("")
        self.SongKey.addItem("")
        self.SongKey.addItem("")
        self.SongKey.addItem("")
        self.SongKey.addItem("")
        self.SongKey.addItem("")
        self.SongKey.addItem("")
        self.SongKey.addItem("")
        self.SongKey.addItem("")
        self.SongKey.addItem("")
        self.SongKey.addItem("")
        self.horizontalLayout.addWidget(self.SongKey)
        self.gridLayout_2.addWidget(self.frame_2, 2, 0, 1, 2)

        self.retranslateUi(Dialog)
        self.buttonBox.accepted.connect(Dialog.accept)
        self.buttonBox.rejected.connect(Dialog.reject)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.label.setText(_translate("Dialog", "File Name:"))
        self.SongKey.setItemText(0, _translate("Dialog", "C"))
        self.SongKey.setItemText(1, _translate("Dialog", "Db"))
        self.SongKey.setItemText(2, _translate("Dialog", "D"))
        self.SongKey.setItemText(3, _translate("Dialog", "Eb"))
        self.SongKey.setItemText(4, _translate("Dialog", "E"))
        self.SongKey.setItemText(5, _translate("Dialog", "F"))
        self.SongKey.setItemText(6, _translate("Dialog", "Gb"))
        self.SongKey.setItemText(7, _translate("Dialog", "G"))
        self.SongKey.setItemText(8, _translate("Dialog", "Ab"))
        self.SongKey.setItemText(9, _translate("Dialog", "A"))
        self.SongKey.setItemText(10, _translate("Dialog", "Bb"))
        self.SongKey.setItemText(11, _translate("Dialog", "B"))
