# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Prefs.ui'
#
# Created by: PyQt5 UI code generator 5.13.2
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_PrefsEditor(object):
    def setupUi(self, PrefsEditor):
        PrefsEditor.setObjectName("PrefsEditor")
        PrefsEditor.resize(1024, 500)
        PrefsEditor.setMinimumSize(QtCore.QSize(1024, 500))
        self.verticalLayout = QtWidgets.QVBoxLayout(PrefsEditor)
        self.verticalLayout.setObjectName("verticalLayout")
        self.frame = QtWidgets.QFrame(PrefsEditor)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frame.sizePolicy().hasHeightForWidth())
        self.frame.setSizePolicy(sizePolicy)
        self.frame.setMaximumSize(QtCore.QSize(2000, 16777215))
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.gridLayout = QtWidgets.QGridLayout(self.frame)
        self.gridLayout.setObjectName("gridLayout")
        self.label = QtWidgets.QLabel(self.frame)
        font = QtGui.QFont()
        font.setPointSize(11)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.gridLayout.addWidget(self.label, 0, 0, 1, 1)
        self.frame_3 = QtWidgets.QFrame(self.frame)
        self.frame_3.setMinimumSize(QtCore.QSize(0, 30))
        self.frame_3.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_3.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_3.setObjectName("frame_3")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.frame_3)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.label_4 = QtWidgets.QLabel(self.frame_3)
        self.label_4.setMinimumSize(QtCore.QSize(250, 0))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.label_4.setFont(font)
        self.label_4.setWordWrap(True)
        self.label_4.setObjectName("label_4")
        self.gridLayout_3.addWidget(self.label_4, 0, 3, 1, 1)
        self.PageSize = QtWidgets.QComboBox(self.frame_3)
        self.PageSize.setMinimumSize(QtCore.QSize(75, 30))
        self.PageSize.setMaximumSize(QtCore.QSize(30, 20))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.PageSize.setFont(font)
        self.PageSize.setObjectName("PageSize")
        self.PageSize.addItem("")
        self.PageSize.addItem("")
        self.PageSize.addItem("")
        self.PageSize.addItem("")
        self.PageSize.addItem("")
        self.PageSize.addItem("")
        self.PageSize.addItem("")
        self.PageSize.addItem("")
        self.PageSize.addItem("")
        self.PageSize.addItem("")
        self.PageSize.addItem("")
        self.PageSize.addItem("")
        self.PageSize.addItem("")
        self.PageSize.addItem("")
        self.PageSize.addItem("")
        self.PageSize.addItem("")
        self.PageSize.addItem("")
        self.PageSize.addItem("")
        self.PageSize.addItem("")
        self.PageSize.addItem("")
        self.PageSize.addItem("")
        self.PageSize.addItem("")
        self.PageSize.addItem("")
        self.PageSize.addItem("")
        self.PageSize.addItem("")
        self.PageSize.addItem("")
        self.PageSize.addItem("")
        self.PageSize.addItem("")
        self.PageSize.addItem("")
        self.PageSize.addItem("")
        self.PageSize.addItem("")
        self.gridLayout_3.addWidget(self.PageSize, 0, 4, 1, 1)
        self.DefaultFontSize = QtWidgets.QComboBox(self.frame_3)
        self.DefaultFontSize.setMinimumSize(QtCore.QSize(75, 20))
        self.DefaultFontSize.setMaximumSize(QtCore.QSize(60, 30))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.DefaultFontSize.setFont(font)
        self.DefaultFontSize.setObjectName("DefaultFontSize")
        self.DefaultFontSize.addItem("")
        self.DefaultFontSize.addItem("")
        self.DefaultFontSize.addItem("")
        self.DefaultFontSize.addItem("")
        self.DefaultFontSize.addItem("")
        self.DefaultFontSize.addItem("")
        self.DefaultFontSize.addItem("")
        self.gridLayout_3.addWidget(self.DefaultFontSize, 0, 1, 1, 1)
        self.label_2 = QtWidgets.QLabel(self.frame_3)
        self.label_2.setMinimumSize(QtCore.QSize(200, 0))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.label_2.setFont(font)
        self.label_2.setWordWrap(True)
        self.label_2.setObjectName("label_2")
        self.gridLayout_3.addWidget(self.label_2, 0, 0, 1, 1)
        self.label_5 = QtWidgets.QLabel(self.frame_3)
        self.label_5.setMaximumSize(QtCore.QSize(50, 16777185))
        self.label_5.setObjectName("label_5")
        self.gridLayout_3.addWidget(self.label_5, 0, 2, 1, 1)
        self.gridLayout.addWidget(self.frame_3, 1, 0, 1, 3)
        self.frame_2 = QtWidgets.QFrame(self.frame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frame_2.sizePolicy().hasHeightForWidth())
        self.frame_2.setSizePolicy(sizePolicy)
        self.frame_2.setMinimumSize(QtCore.QSize(0, 127))
        self.frame_2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_2.setObjectName("frame_2")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.frame_2)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.label_3 = QtWidgets.QLabel(self.frame_2)
        font = QtGui.QFont()
        font.setPointSize(11)
        self.label_3.setFont(font)
        self.label_3.setWordWrap(True)
        self.label_3.setObjectName("label_3")
        self.gridLayout_2.addWidget(self.label_3, 0, 0, 2, 1)
        self.groupBox_2 = QtWidgets.QGroupBox(self.frame_2)
        self.groupBox_2.setMinimumSize(QtCore.QSize(0, 30))
        self.groupBox_2.setTitle("")
        self.groupBox_2.setObjectName("groupBox_2")
        self.radioButton_Ds = QtWidgets.QRadioButton(self.groupBox_2)
        self.radioButton_Ds.setGeometry(QtCore.QRect(0, 0, 62, 30))
        self.radioButton_Ds.setMinimumSize(QtCore.QSize(0, 30))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.radioButton_Ds.setFont(font)
        self.radioButton_Ds.setObjectName("radioButton_Ds")
        self.radioButton_Eb = QtWidgets.QRadioButton(self.groupBox_2)
        self.radioButton_Eb.setGeometry(QtCore.QRect(70, 0, 62, 30))
        self.radioButton_Eb.setMinimumSize(QtCore.QSize(0, 30))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.radioButton_Eb.setFont(font)
        self.radioButton_Eb.setObjectName("radioButton_Eb")
        self.gridLayout_2.addWidget(self.groupBox_2, 1, 1, 1, 1)
        self.groupBox_3 = QtWidgets.QGroupBox(self.frame_2)
        self.groupBox_3.setMinimumSize(QtCore.QSize(0, 30))
        self.groupBox_3.setTitle("")
        self.groupBox_3.setObjectName("groupBox_3")
        self.radioButton_Fs = QtWidgets.QRadioButton(self.groupBox_3)
        self.radioButton_Fs.setGeometry(QtCore.QRect(0, 0, 62, 30))
        self.radioButton_Fs.setMinimumSize(QtCore.QSize(0, 30))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.radioButton_Fs.setFont(font)
        self.radioButton_Fs.setObjectName("radioButton_Fs")
        self.radioButton_Gb = QtWidgets.QRadioButton(self.groupBox_3)
        self.radioButton_Gb.setGeometry(QtCore.QRect(70, 0, 62, 30))
        self.radioButton_Gb.setMinimumSize(QtCore.QSize(0, 30))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.radioButton_Gb.setFont(font)
        self.radioButton_Gb.setObjectName("radioButton_Gb")
        self.gridLayout_2.addWidget(self.groupBox_3, 2, 1, 1, 1)
        self.groupBox_4 = QtWidgets.QGroupBox(self.frame_2)
        self.groupBox_4.setMinimumSize(QtCore.QSize(0, 30))
        self.groupBox_4.setTitle("")
        self.groupBox_4.setObjectName("groupBox_4")
        self.radioButton_Gs = QtWidgets.QRadioButton(self.groupBox_4)
        self.radioButton_Gs.setGeometry(QtCore.QRect(0, 0, 62, 30))
        self.radioButton_Gs.setMinimumSize(QtCore.QSize(0, 30))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.radioButton_Gs.setFont(font)
        self.radioButton_Gs.setObjectName("radioButton_Gs")
        self.radioButton_Ab = QtWidgets.QRadioButton(self.groupBox_4)
        self.radioButton_Ab.setGeometry(QtCore.QRect(70, 0, 62, 30))
        self.radioButton_Ab.setMinimumSize(QtCore.QSize(0, 30))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.radioButton_Ab.setFont(font)
        self.radioButton_Ab.setObjectName("radioButton_Ab")
        self.gridLayout_2.addWidget(self.groupBox_4, 3, 1, 1, 1)
        self.groupBox_1 = QtWidgets.QGroupBox(self.frame_2)
        self.groupBox_1.setMinimumSize(QtCore.QSize(0, 30))
        self.groupBox_1.setTitle("")
        self.groupBox_1.setObjectName("groupBox_1")
        self.radioButton_Cs = QtWidgets.QRadioButton(self.groupBox_1)
        self.radioButton_Cs.setGeometry(QtCore.QRect(0, 0, 62, 30))
        self.radioButton_Cs.setMinimumSize(QtCore.QSize(0, 30))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.radioButton_Cs.setFont(font)
        self.radioButton_Cs.setObjectName("radioButton_Cs")
        self.radioButton_Db = QtWidgets.QRadioButton(self.groupBox_1)
        self.radioButton_Db.setGeometry(QtCore.QRect(70, 0, 62, 30))
        self.radioButton_Db.setMinimumSize(QtCore.QSize(0, 30))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.radioButton_Db.setFont(font)
        self.radioButton_Db.setObjectName("radioButton_Db")
        self.gridLayout_2.addWidget(self.groupBox_1, 0, 1, 1, 1)
        self.groupBox_5 = QtWidgets.QGroupBox(self.frame_2)
        self.groupBox_5.setMinimumSize(QtCore.QSize(0, 30))
        self.groupBox_5.setTitle("")
        self.groupBox_5.setObjectName("groupBox_5")
        self.radioButton_As = QtWidgets.QRadioButton(self.groupBox_5)
        self.radioButton_As.setGeometry(QtCore.QRect(0, 0, 62, 30))
        self.radioButton_As.setMinimumSize(QtCore.QSize(0, 30))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.radioButton_As.setFont(font)
        self.radioButton_As.setObjectName("radioButton_As")
        self.radioButton_Bb = QtWidgets.QRadioButton(self.groupBox_5)
        self.radioButton_Bb.setGeometry(QtCore.QRect(70, 0, 62, 30))
        self.radioButton_Bb.setMinimumSize(QtCore.QSize(0, 30))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.radioButton_Bb.setFont(font)
        self.radioButton_Bb.setObjectName("radioButton_Bb")
        self.gridLayout_2.addWidget(self.groupBox_5, 4, 1, 1, 1)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_2.addItem(spacerItem, 1, 2, 1, 1)
        self.gridLayout.addWidget(self.frame_2, 2, 0, 1, 4)
        self.SongDirectory = QtWidgets.QLineEdit(self.frame)
        font = QtGui.QFont()
        font.setPointSize(11)
        self.SongDirectory.setFont(font)
        self.SongDirectory.setObjectName("SongDirectory")
        self.gridLayout.addWidget(self.SongDirectory, 0, 1, 1, 1)
        self.pushBrowse = QtWidgets.QPushButton(self.frame)
        self.pushBrowse.setObjectName("pushBrowse")
        self.gridLayout.addWidget(self.pushBrowse, 0, 3, 1, 1)
        self.verticalLayout.addWidget(self.frame)
        self.buttonBox = QtWidgets.QDialogButtonBox(PrefsEditor)
        self.buttonBox.setOrientation(QtCore.Qt.Horizontal)
        self.buttonBox.setStandardButtons(QtWidgets.QDialogButtonBox.Cancel|QtWidgets.QDialogButtonBox.Ok)
        self.buttonBox.setObjectName("buttonBox")
        self.verticalLayout.addWidget(self.buttonBox)

        self.retranslateUi(PrefsEditor)
        self.buttonBox.accepted.connect(PrefsEditor.accept)
        self.buttonBox.rejected.connect(PrefsEditor.reject)
        QtCore.QMetaObject.connectSlotsByName(PrefsEditor)

    def retranslateUi(self, PrefsEditor):
        _translate = QtCore.QCoreApplication.translate
        PrefsEditor.setWindowTitle(_translate("PrefsEditor", "Dialog"))
        self.label.setText(_translate("PrefsEditor", "Directory of Songs:"))
        self.label_4.setText(_translate("PrefsEditor", "Default # lines before column Split"))
        self.PageSize.setItemText(0, _translate("PrefsEditor", "20"))
        self.PageSize.setItemText(1, _translate("PrefsEditor", "21"))
        self.PageSize.setItemText(2, _translate("PrefsEditor", "22"))
        self.PageSize.setItemText(3, _translate("PrefsEditor", "23"))
        self.PageSize.setItemText(4, _translate("PrefsEditor", "24"))
        self.PageSize.setItemText(5, _translate("PrefsEditor", "25"))
        self.PageSize.setItemText(6, _translate("PrefsEditor", "26"))
        self.PageSize.setItemText(7, _translate("PrefsEditor", "27"))
        self.PageSize.setItemText(8, _translate("PrefsEditor", "28"))
        self.PageSize.setItemText(9, _translate("PrefsEditor", "29"))
        self.PageSize.setItemText(10, _translate("PrefsEditor", "30"))
        self.PageSize.setItemText(11, _translate("PrefsEditor", "31"))
        self.PageSize.setItemText(12, _translate("PrefsEditor", "32"))
        self.PageSize.setItemText(13, _translate("PrefsEditor", "33"))
        self.PageSize.setItemText(14, _translate("PrefsEditor", "34"))
        self.PageSize.setItemText(15, _translate("PrefsEditor", "35"))
        self.PageSize.setItemText(16, _translate("PrefsEditor", "36"))
        self.PageSize.setItemText(17, _translate("PrefsEditor", "37"))
        self.PageSize.setItemText(18, _translate("PrefsEditor", "38"))
        self.PageSize.setItemText(19, _translate("PrefsEditor", "39"))
        self.PageSize.setItemText(20, _translate("PrefsEditor", "40"))
        self.PageSize.setItemText(21, _translate("PrefsEditor", "41"))
        self.PageSize.setItemText(22, _translate("PrefsEditor", "42"))
        self.PageSize.setItemText(23, _translate("PrefsEditor", "43"))
        self.PageSize.setItemText(24, _translate("PrefsEditor", "44"))
        self.PageSize.setItemText(25, _translate("PrefsEditor", "45"))
        self.PageSize.setItemText(26, _translate("PrefsEditor", "46"))
        self.PageSize.setItemText(27, _translate("PrefsEditor", "47"))
        self.PageSize.setItemText(28, _translate("PrefsEditor", "48"))
        self.PageSize.setItemText(29, _translate("PrefsEditor", "49"))
        self.PageSize.setItemText(30, _translate("PrefsEditor", "50"))
        self.DefaultFontSize.setItemText(0, _translate("PrefsEditor", "10"))
        self.DefaultFontSize.setItemText(1, _translate("PrefsEditor", "15"))
        self.DefaultFontSize.setItemText(2, _translate("PrefsEditor", "20"))
        self.DefaultFontSize.setItemText(3, _translate("PrefsEditor", "25"))
        self.DefaultFontSize.setItemText(4, _translate("PrefsEditor", "30"))
        self.DefaultFontSize.setItemText(5, _translate("PrefsEditor", "35"))
        self.DefaultFontSize.setItemText(6, _translate("PrefsEditor", "40"))
        self.label_2.setText(_translate("PrefsEditor", "Default Font Size of Song Text"))
        self.label_5.setText(_translate("PrefsEditor", " "))
        self.label_3.setText(_translate("PrefsEditor", "Sharps / Flats Preference"))
        self.radioButton_Ds.setText(_translate("PrefsEditor", "D#"))
        self.radioButton_Eb.setText(_translate("PrefsEditor", "Eb"))
        self.radioButton_Fs.setText(_translate("PrefsEditor", "F#"))
        self.radioButton_Gb.setText(_translate("PrefsEditor", "Gb"))
        self.radioButton_Gs.setText(_translate("PrefsEditor", "G#"))
        self.radioButton_Ab.setText(_translate("PrefsEditor", "Ab"))
        self.radioButton_Cs.setText(_translate("PrefsEditor", "C#"))
        self.radioButton_Db.setText(_translate("PrefsEditor", "Db"))
        self.radioButton_As.setText(_translate("PrefsEditor", "A#"))
        self.radioButton_Bb.setText(_translate("PrefsEditor", "Bb"))
        self.pushBrowse.setText(_translate("PrefsEditor", "Browse"))
